roocs/rook

- environment.yml
This PR adds the clisops conda package to the environment. It removes the unnecessary gunicorn package.
> use clisops, skip gunicorn

- tests/common.py
Removed quotes from c3s-cmip6 base dir in config template for tests
> removed quotes from config test template

- tests/__init__.py
- tests/common.py
- tests/conftest.py
This PR adds `tests/conftest.py` with the init of the `roocs.ini` config file.
PR https://github.com/roocs/dachar/pull/82
> use conftest to set roocs config

- rook/processes/wps_subset.py
- setup.cfg
- tests/test_wps_subset.py
This PR removes the default values in wps subset process. The `time` parameter is mandatory.
https://github.com/roocs/34e-mngmt/issues/42
> skip defaults in wps subset process

- notebooks/environment.yml
- notebooks/rook-demo.ipynb
- rook/processes/wps_average.py
- rook/processes/wps_orchestrate.py
- rook/processes/wps_subset.py
- tests/test_wps_orchestrate.py
- tests/test_wps_subset.py
This PR keeps only the metalink output parameter in all wps processes. Update notebook example and pymetalink library.
https://github.com/roocs/34e-mngmt/issues/42
> Use only metalink output

- etc/roocs-dev.ini
- etc/roocs.ini
- notebooks/rook-demo.ipynb
- rook/processes/wps_average.py
- rook/processes/wps_subset.py
- tests/test_wps_average.py
- tests/test_wps_subset.py
This PR updates the wps abstracts with c3s-cmip5 default data.
Changes:
* Updated demo notebook.
* Updated tests.
* Updates mini-esgf-data.
> using c3s-cmip5 data as default

- .travis.yml
- env.yml
- environment.yml
- etc/debug.cfg
- rook/processes/wps_subset.py
- setup.py
- spec-list.txt
This PR uses a patched version of clisops to avoid process blocking: 
https://github.com/roocs/clisops/pull/55
Updated conda env. Testing only with Python 3.7
> using patched clisops, update conda env

- rook/processes/wps_orchestrate.py
- rook/workflow.py
This PR adds a workaround to strip `CDATA` tag from the workflow json input. 
Needs to be fixed in pywps.
https://github.com/geopython/pywps/issues/553
> added workaround for cdata issue

- tests/test_wps_subset.py
Adds a test for a time invariant dataset. Works with changes made to file name template in the equivalent `daops`, `clisops` and `roocs-utils` branches (`test_time_invariant_datasets`, `test_time_invariant_datasets` and `time_invariant_datasets`)
> add test for time invariant dataset

- rook/processes/wps_orchestrate.py
- rook/processes/wps_subset.py
- rook/utils/metalink_utils.py
- tests/test_utils.py
This PR fixes `build_metalink` to set urls and files.
Changes:
* `build_metalink` figures out by itself it `file_uri` is a url or file.
* test added.
#92
> fix build_metalink for urls returned by workflow

- rook/operator.py
- rook/workflow.py
This PR is a workaround for issue #110. 
Changes:
* Disabled `apply_fixes` in workflow.
#110
> quick fix: disable apply_fixes in workflow

- rook/provenance.py
- setup.py
- tests/common.py
- tests/test_wps_subset.py
This PR fixes #113.
Changes:
* Fixed provenance to return all outputs.
* Added test for prov with multiple output files.
* Updated "no inventory" test
* Updated `roocs.ini` template for tests to split files at 100KB.
Fix #113
> Fix prov multiple files

- setup.cfg
- tests/test_workflow.py
Remove `pytest.mark.xfail` for tests that no longer need it.
A `use_inventory` option has been implemented so that cmip5 tests don't need a mock inventory.
> removed xfails where not needed

- requirements_dev.txt
- tests/common.py
- tests/conftest.py
- tests/test_director/test_alignment.py
- tests/test_utils.py
Removed `mini-esgf-data` submodule in favour of cloning it it when needed for tests. This is done using a new pytest fixture `load_test_data` which implements the `GitPython` library (now added to `requirements_dev.txt`)
> Gitpython testdata fix

- CHANGES.rst
- environment.yml
- requirements.txt
This PR updates the requirements and changes for release 0.3.1.
We need to pin `cf_xarray <0.5.0` ... it does not work with `daops/clisops`.
> Release 0.3.1

- tests/test_director/test_director.py
- tests/test_director/test_inv_cache.py
- tests/test_wps_orchestrate.py
- tests/test_wps_subset.py
- tests/testdata/subset_wf_5.json
- tests/testdata/wf_cmip6_subset_average.json
- tests/testdata/wf_cmip6_subset_average_with_fixes.json
This PR fixes the test suite.
The tests for cmip6 were using the following dataset:
```
c3s-cmip6.CMIP.IPSL.IPSL-CM6A-LR.historical.r1i1p1f1.Amon.rlds.gr.v20180803
```
This one is not available anymore in the inventory catalog starting from 01.03.2021.
I have not found a good replacement both available in the catalog and in the testdata.
Changes:
* Using `CMIP6.` dataset to avoid inventory check.
* xfail `TestDirectorCMIP6`
> fixed tests ... using CMIP6 dataset

- rook/processes/wps_average.py
Elasticsearch was down on Tuesday and the average tests were failing. It made me realise we had the default for average as `apply_fixes=True`. I've changed it to `apply_fixes=False` to be consistent with subset.
> Change default behaviour for apply fixes for average

- tests/smoke/conftest.py
This PR is a workaround for an issue with pywps when using scheduler backend. Outputs were given always by reference, though it was requested to be included in the response document.
Now, we always retrieve in smoke the `output` via reference.
> Fix smoke: output via reference

- requirements_dev.txt
- tests/storm/locustfile.py
This PR fixes a dependency installation and modifies the default host URL for the Locust swarm tests.
Changes:
* Added package to test dependencies: `pyquery`
* Change default locust host to remove `/wps` in URL, as it is not needed.
Relates to: https://github.com/roocs/34e-mngmt/issues/91
> Updates for locust tests

- environment.yml
- requirements.txt
- rook/default.cfg
- rook/utils/metalink_utils.py
- setup.cfg
- tests/test_director/test_director.py
- tests/test_workflow.py
- tests/test_wps_orchestrate.py
- tests/test_wps_subset.py
- tests/testdata/wf_c3s_cmip6_subset_collection_only.json
This PR fixes the test suite
Changes:
* Using latest pywps with a fix metalink: https://github.com/geopython/pywps/pull/581
* Updated director tests with a new test dataset
* Updated pywps `default.cfg` description ... removed unnecessary `maxsingleinputsize` parameter
* Updated tests to use `c3s-cmip6` datasets
The metalink document skips file size calculation for URLs. URLs are set for "original" files from `https://data.mips.copernicus-climate.eu`. File size calculation takes too long when many files are added (>100).
TODO: we need to have file size in our inventory/catalog, so we can set it without retrieving it via `get` requests.
> fix tests, using latest pywps

- rook/director/director.py
- rook/workflow.py
- setup.cfg
- tests/smoke/conftest.py
- tests/smoke/test_smoke_checks.py
- tests/smoke/utils.py
This PR fixes #168.
Changes:
* Using `FileMapper` to bundle files of a single dataset.
* Updated smoke tests to check if a collection with several files are handled as single dataset.
* `test_smoke_execute_c3s_cmip6_day_average_time` ... 2 input files ... one output file.
Fix #168
> use FileMapper for search results

- CHANGES.rst
- environment-docs.yml
- environment.yml
- requirements.txt
- requirements_dev.txt
- rook/catalog/db.py
This PR updates the versions of `roocs-utils`, `clisops` and `daops`
After this rook can be released to allow the next intake catalogue to be used.
Changes:
* Also added in a section to `db.py` to make compatible with next catalogue which uses "undefined" for `start_time` and `end_time` when there is no time dimension.
* Restricted the sphinx version to 3.5.4 as latest version raises an error, as mentioned here https://github.com/geopython/pywps/issues/608
> Changes for release

- rook/provenance.py
This PR updates the provenance to climate4impact terminology.
Changes:
* Renamed namespace `dcterms` to `dct`.
> renamed dctermns to dct

- environment.yml
- requirements.txt
- requirements_dev.txt
- rook/director/director.py
- rook/operator.py
- rook/processes/wps_average.py
- rook/processes/wps_subset.py
- rook/workflow.py
- tests/common.py
- tests/test_wps_cmip6_decadal.py
Changes:
* Added test for cmip6 decadal.
* Use fixes by default.
* Uses `check_apply_fixes()` to check if a fix is available and will be applied. 
* Updates `apply_fixes` parameter accordingly and this will be documented in the provenance.
The cmip6 decadal is `xfailed` because the cmip6 decdal is not in the c3s-cmip6 catalog. Need disable the catalog check in `roocs.ini` to run the test:
```
[project:c3s-cmip6]
use_catalog = False
```
Fix #201
> Switch on apply fixes

- rook/operator.py
- rook/provenance.py
- rook/workflow.py
- tests/test_workflow.py
This PR cleans up the workflow tests.
Changes:
* Using pytest `tmp_path`.
* Using `pathlib.Path` in workflow, operator and provenance.
* Renamed `TreeWorkflow` to `Workflow`.
> Cleanup workflow tests

- rook/provenance.py
This PR the provenance information as requested by c4i.
Changes:
* Rename `dct` to `dcterms`.
> Update prov c4i

- tests/smoke/test_smoke_checks.py
This PR fixes cmip5 smoke tests. Using a cmip5 ds-id from the current catalog.
> fix cmip5 smoke tests

- rook/processes/wps_regrid.py
- rook/provenance.py
- tests/test_wps_regrid.py
This PR updates the parameters of the regrid operator:
* grid: auto (default), 0pt25deg, 0pt25deg_era5, 0pt5deg_lsm,  0pt625x0pt5deg, 0pt75deg, 1deg, 1pt25deg, 2pt5deg
* method: nearest_s2d (default), bilinear, conservative,  patch
* adaptive_masking_threshold: 0.5
> update regrid parameters

- environment.yml
- requirements.txt
- rook/utils/concat_utils.py
- rook/utils/decadal_fixes.py
This PR update the cmip6 decadal fixes.
Changes:
* Set new data variable `realization` to the value of `realization_index`.
* Use the variable `realization` in the concat operation instead of the `realization_index`.
* Don't use the cf standard name for `realization`.
> Update decadal fixes

- .github/workflows/main.yml
- environment.yml
- requirements.txt
This PR allows latest pywps version 4.6.x.
Changes:
* update pywps
* run tests also on Python 3.11
> allow pywps 4.6.x

- rook/utils/concat_utils.py
This PR updates the concat operator to set the cf-standard of the realization coord. This is need for the `average_over_dim` operator.
> added cf standard-name to realization coord

- rook/processes/wps_concat.py
- rook/processes/wps_subset.py
- rook/utils/concat_utils.py
- rook/utils/input_utils.py
- rook/utils/subset_utils.py
- tests/smoke/test_smoke_checks.py
- tests/test_utils.py
This PR fixes an issue with 360day calendars. It removes redundant parts from the `time_component` to avoid the selection of day 31. 
Changes:
* Added `fix_time_componets` in  `input_utils`.
* Use `fix_time_components` in subset and concat operator.
* Added tests.
https://nbviewer.org/github/roocs/rooki/blob/master/notebooks/errors/cds-error-2023-12-05-360day-calendar.ipynb
> Fix time components

- .github/CONTRIBUTING.md
- README.rst
- src/rook/default.cfg
Some documentation links referred to https://rook.readthedocs.io (a different project: https://github.com/AvisoNovate/rook). The actual documentation is at https://rook-wps.readthedocs.io
Changes:
* Fixed documentation links
> Fix documentation links

- .cruft.json
- CHANGELOG.rst
- Dockerfile
- pyproject.toml
- src/rook/__version__.py
This PR prepares the release 0.15.0.
This release includes an update for the decadal fixes and the provenance document.
Changes:
* Updated history.
* Updated version number.
> Prep rel 0.15.0

- .github/workflows/main.yml
- README.rst
- pyproject.toml
This PR updates the configs and docs to use now the `main` branch instead of `master`.
> renamed branch master to main

- environment-dev.yml
- environment.yml
- pyproject.toml
- src/rook/utils/decadal_fixes.py
- src/rook/utils/metalink_utils.py
- src/rook/workflow.py
- tests/conftest.py
- tests/smoke/conftest.py
- tests/test_wps_average_dim.py
- tests/test_wps_average_shape.py
- tests/test_wps_average_time.py
- tests/test_wps_average_weighted.py
- tests/test_wps_cmip6_decadal.py
- tests/test_wps_concat.py
- tests/test_wps_orchestrate.py
- tests/test_wps_regrid.py
- tests/test_wps_subset.py
This PR fixes the smoke tests.
Changes:
* use posix path for pywps config
* using parse_metalink and extract_paths_from_metalink from metalink_utils in tests
* added open_dataset fixture
* using pywps_cfg fixture
* beautifulsoup4 is now a required dependency
> Fix smoke tests
