roocs/rook

examples/workflow/wf-wind-speed-1.json, examples/workflow/wf-wind-speed-2.json, examples/workflow/wf-wind-speed-3.json, examples/workflow/wf-wind-speed-4.json
This PR adds example workflow descriptions. Prototypes only.
=> added workflow examples

.gitmodules, .travis.yml, docs/source/installation.rst, roocswps/processes/wps_orchestrate.py, roocswps/processes/wps_subset.py, setup.cfg, tests/common.py, tests/test_wps_orchestrate.py, tests/test_wps_subset.py
This PR adds the mini-esgf-data for testing.
Changes:
* Added submodule mini-esgf-data.
* Updated tests with generated `pywps_test.cfg`.
=> using mini esgf test data

.travis.yml, environment.yml, notebooks/roocs-demo.ipynb, requirements.txt, roocswps/exceptions.py, roocswps/processes/wps_orchestrate.py, roocswps/workflow.py, setup.cfg, tests/common.py, tests/test_workflow.py, tests/test_wps_orchestrate.py, tests/testdata/subset_simple_wf.json, tests/testdata/subset_wf_1.json
This PR adds a workflow module with a "simple chain" and a "function tree" workflow.
=> added function tree workflow

notebooks/roocs-demo.ipynb, roocswps/workflow.py, tests/test_workflow.py, tests/testdata/subset_wf_2.json
This PR introduces the `Operator` class for `subset` and `average` and fixes the temp folder generation.
=> fix workflow temp folders

etc/demo.cfg, etc/pingudev.cfg, notebooks/roocs-demo.ipynb, roocswps/operator.py, roocswps/workflow.py, tests/test_workflow.py, tests/testdata/subset_wf_3.json
This PR adds a tree workflow with a `diff` operator with two `data_ref` inputs. The `workflow` module has been extended to support operators with multiple inputs.
=> added diff workflow

tests/testdata/subset_wf_3.json
This PR fixes the test for the "diff" workflow.
=> fix wf diff test

notebooks/rook-demo.ipynb, rook/processes/wps_orchestrate.py, rook/workflow.py, tests/test_workflow.py
This PR adds a `WorkflowRunner` which automatically discovers workflow mode: simple or tree.
https://github.com/roocs/rooki/issues/7
=> added workflow runner

.cruft.json, Dockerfile, environment.yml
This PR adds changes for conda env from template (using cruft).
=> update from cruft

.cruft.json, Dockerfile, environment.yml
This PR adds an update by cruft (template) for using conda env in Dockerfile.
=> cruft update .. dockerfile

rook/operator.py, rook/processes/wps_average.py, rook/processes/wps_subset.py
This PR prevents to import `daops` when starting the wps service.
=> lazy load daops

environment.yml
This PR updates the conda env to fix issues with ansible deployment.
https://github.com/bird-house/ansible-wps-playbook/issues/96
=> fix conda env for ansible deployment

environment.yml, notebooks/rook-demo.ipynb, requirements.txt
This PR updates to latest clisops (0.3.0) and testdata. Cleaned up workflow example notebook.
=> update clisops, testdata and notebook

environment.yml
This PR fixes `cfunits` dependencies in conda env.
=> fix cfunits in conda env

.travis.yml, environment.yml, rook/processes/wps_orchestrate.py, rook/processes/wps_subset.py, rook/utils.py
This PR uses a patched pywps with fixes:
* `ProcessError` with formatting: https://github.com/geopython/pywps/pull/546
*  Scheduler extension with config for DRMAA: https://github.com/geopython/pywps/pull/547
https://github.com/natefoo/slurm-drmaa
=> using patched pywps with fix for ProcessError

.cruft.json, .readthedocs.yml, .travis.yml, Dockerfile, Makefile, docs/Makefile, docs/source/conf.py, requirements_dev.txt, setup.cfg
This PR adds changes from template update with `cruft update`.
https://cookiecutter-birdhouse.readthedocs.io/en/latest/
=> updated from template with cruft

.travis.yml, docs/source/conf.py, docs/source/index.rst, environment-docs.yml
This PR disables notebook rendering for sphinx docs.
#62
=> disable notebook rendering

environment.yml, requirements.txt, rook/operator.py, rook/processes/wps_subset.py
This fixes the import error with parameterise and uses the pypi package for roocs-utils
=> Parameterise import

CHANGES.rst, environment.yml, requirements.txt, rook/operator.py, rook/processes/wps_average.py, rook/processes/wps_subset.py, setup.py
This PR is for https://github.com/roocs/34e-mngmt/issues/68
Changes:
* Add apply fixes option
Following on from the call on Friday - I'm still not really sure what to do about the `daops` version. I've added the `apply_fixes` `daops` branch into `install_requires` but let me know what is best.
=> Apply fixes option

rook/operator.py, rook/processes/wps_subset.py
Fix so that master will work with update in `daops`
=> updated to use file_uris instead of file_paths

.pre-commit-config.yaml, requirements_dev.txt, rook/operator.py
This PR fixes the chaining in the workflow. 
Changes:
* Use a directory with input files for the follow-up operators in a workflow chain. Implemented for `subset`.
* Added `black` and `pre-commit`.
Based on this code:
https://gist.github.com/agstephens/3046307e1de0594c858207fa60850a40
=> Fix workflow chain

rook/director/alignment.py, tests/test_director/test_alignment.py
This PR fixes [issue id]
Changes:
* Added ...
=> Updated alignment to fix issue:#100

CHANGES.rst, environment.yml, requirements.txt
This PR updates to pywps 4.4.0
=> update pywps 4.4.0

CHANGES.rst, environment.yml, requirements.txt
This PR updates the changes and the requirements for release 0.3.0.
=> Release 0.3.0

.github/workflows/main.yml, CHANGES.rst, README.rst, tests/smoke/test_smoke_checks.py
This PR prepares the release 0.4.0
Changes:
* Update changes
* Fixed CI badge in readme
* Added average tests to smoke-tests
=> Release 0.4.0

requirements_dev.txt, tests/storm/common.py, tests/storm/locustfile.py, tests/storm/templates/execute.xml, tests/test_director/test_inv_cache.py
This PR adds an initial set of "storm" tests using [locust](https://locust.io/).
Changes:
* Added storm tests.
Run with:
```
locust -f tests/storm/locustfile.py 
```
https://github.com/roocs/34e-mngmt/issues/91
https://github.com/pglass/how-do-i-locust
=> added storm (locust) tests

rook/default.cfg, rook/workflow.py, tests/pywps.cfg, tests/smoke/test_smoke_checks.py
This PR fixes issue #138.  
Changes:
* Added a yaml loader.
* Updates smoke test for issue #139
* Updated default pywps config: `maxsingleinputsize = 10gb`
#138, #139
=> Fix workflow yaml load

environment.yml, requirements.txt
This PR cleans the requirements.
=> clean requirements

rook/director/director.py, rook/exceptions.py, tests/test_director/test_director.py
This PR updates the director.
Changes:
* Added exception `InvalidCollection` used by `Director`.
* Added test for `InvalidCollection`
=> Updated director with InvalidCollection error

rook/default.cfg, tests/pywps.cfg, tests/test_wps_average.py
This PR adds the pywps `storage_copy_function=link`. It creates a hardlink with `os.link` when copying files to the output folder.  
Fix #146 
PR in pywps: https://github.com/geopython/pywps/pull/584
=> use pywps storage_copy_function=link

environment.yml
This PR adds latest pywps 4.4.1 from conda with metalink fixes.
=> use pywps from conda

CHANGES.rst, environment.yml, requirements.txt
This PR prepares release 0.5.0.
Changes:
* Updated changes.
* Updated dependencies: pywps, clisops, roocs-utils.
=> Release 0.5.0

.gitmodules, README.rst, docs/source/dev_guide.rst, docs/source/installation.rst, environment.yml, requirements.txt
This PR fixes #170.
Changes:
* Updated dev guide.
* Added links to additional smoke/storm tests in readme.
* Removed unused `.gitmodules`.
Fix #170.
=> Update storm docs

environment.yml, requirements.txt, rook/processes/wps_average.py, tests/test_wps_average.py
This PR fixes #135 
Changes:
* Added tests to look at behaviour when dims is not provided, when it is an empty string and when it is an unknown dimension
Temporarily use `clisops` master until next `clisops` release
=> Add tests for average when dims is missing/incorrect

notebooks/prov.ipynb, rook/processes/wps_average.py, rook/processes/wps_subset.py, rook/provenance.py, rook/workflow.py, tests/test_provenance.py, tests/test_wps_orchestrate.py, tests/test_wps_subset.py
This PR updates the provenance module.
Changes:
* Using unique IDs with `uuid`.
* Using namespaces for provenance types.
* Using `PROVONE_DATA` for files and `PROVONE_EXECUTION` for operations.
* Adapted prov tests.
=> updated provenance types and ids

CHANGES.rst, environment-docs.yml, requirements_dev.txt
This PR prepares the release for 0.6.2.
Changes:
* Updated release notes.
* Updated dev/doc dependencies for sphinx.
=> Release 0.6.2

.github/workflows/main.yml, environment.yml, requirements.txt, rook/catalog/db.py, rook/director/alignment.py, rook/director/director.py, rook/processes/wps_dashboard.py, rook/processes/wps_subset.py, rook/processes/wps_usage.py, rook/provenance.py, setup.py, tests/smoke/test_smoke_checks.py, tests/test_director/test_alignment.py, tests/test_utils.py, tests/test_wps_subset.py
This PR prepares support for `subset-by-point` (#189). 
Changes:
* Added `time_components` parameter to subset operator.
* Added tests for `time_components`.
https://github.com/roocs/34e-mngmt/issues/105
=> added "subset by point"

.pre-commit-config.yaml, CHANGES.rst, environment.yml, requirements.txt, rook/dashboard/dashboard.py, rook/dashboard/templates/base.html, tests/test_dashboard.py
This PR prepares the release 0.8.0
Changes:
* Updated history.
=> prepare release 0.8.0

environment.yml, requirements.txt, spec-list.txt, tests/smoke/test_smoke_checks.py
This PR updates to latest roocs-utils 0.6.1
Changes:
* Update requirements
* Update smoke tests
=> Update roocs utils

.gitignore, environment.yml, requirements.txt, tests/smoke/test_smoke_checks.py, tests/smoke/utils.py, tests/test_wps_orchestrate.py, tests/test_wps_subset.py, tests/testdata/wf_c3s_cmip6_subset.json
This PR updates clisops and daops with an xarray fix for metadata after an operation.
Changes:
* Updated clisops>=0.9.1
* Added tests to check correct metadata.
=> Fix xarray

rook/etc/roocs.ini
This PR updates the roocs.ini config for `c3s-ipcc-atlas`.
Changes:
* Updated `roocs.ini`
=> add ipcc-atlas

rook/director/director.py
This PR updates the checks if fixes should be used.
=> fix check for applying fixes

rook/processes/__init__.py, rook/processes/wps_average_weighted.py, rook/utils/average_utils.py, tests/test_wps_average_weighted.py, tests/test_wps_caps.py
This PR implements an initial version of a weighted averaging operator.
Changes:
* Added wps process for weighted averaging.
* Added test for weighted averaging process.
* Added dummy operator using average_dim.
=> weighted average operator

rook/operator.py, rook/utils/average_utils.py, rook/workflow.py
This PR updates the weighted-average operator ... work in progess.
Changes:
* Added workflow operator.
=> Update op weighted average

rook/operator.py, rook/processes/__init__.py, rook/processes/wps_regrid.py, rook/provenance.py, rook/utils/regrid_utils.py, rook/workflow.py, tests/test_wps_caps.py, tests/test_wps_regrid.py
This PR adds a new operator regrid.
Changes:
* Added wps regrid process.
* dummy regrid operator implementation.
* regrid operator for workflow
* updated provenance with regrid parameters.
=> Add regrid operator

rook/processes/wps_regrid.py
This PR updates documentation for wps regrid taken from old "regrid-main-elle" branch.
=> updated comments in wps regrid

.github/workflows/main.yml, environment.yml, requirements.txt, setup.cfg, setup.py, tests/smoke/test_smoke_checks.py
This PR adds smoke tests for weighted-average operator. It also skips python 3.8 in testing.
=> Add smoke tests for weighted-average

notebooks/dashboard.ipynb, rook/dashboard/dashboard.py, rook/dashboard/plots/__init__.py, rook/dashboard/plots/day.py, rook/dashboard/plots/hour.py, rook/dashboard/templates/dashboard.html, rook/processes/wps_dashboard.py
This PR improves the dashboard by adding a "day-of-week" and "hour-of-day" plot.
=> Improve dashboard

rook/processes/wps_usage.py, rook/usage/downloads.py
This PR improves the usage collection.
=> Improved usage

src/rook/utils/decadal_fixes.py, src/rook/utils/fixes_utils.py, tests/smoke/test_smoke_checks.py
This PR updates the calendar fix (proleptic gregorian).
See previous fix in PR #263
=> Fix calendar

environment.yml, pyproject.toml, src/rook/dashboard/plots/activity2.py, src/rook/dashboard/plots/concurrency.py, src/rook/dashboard/plots/day.py, src/rook/dashboard/plots/downloads.py, src/rook/dashboard/plots/duration.py, src/rook/dashboard/plots/hour.py, src/rook/dashboard/plots/pulse.py, src/rook/dashboard/plots/transfer.py
This PR updates the dashboard to the latest bokeh version (>=3.7.0).
Changes:
* Replaced attribute plot_height by height.
=> Fix dashboard

.cruft.json, CHANGELOG.rst, Dockerfile, pyproject.toml, src/rook/__version__.py
This PR prepares the patch release 0.17.2 with fixes for the dashboard.
=> Prep rel 0.17.2
